In [1]:
import numpy as np

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [3]:
from sklearn import model_selection
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(X,Y,test_size=0.25,random_state=0)


In [4]:
from sklearn.metrics import confusion_matrix

In [5]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))

[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]


In [6]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))

[[13  0  0]
 [ 0  0 16]
 [ 0  0  9]]
